### ISSUE TITLE
How to display the graphs?

### ISSUE THREAD

**Issue by MightyCreak** [CNRS-DSI-Dev/dashboard#11]
I have no graphs displayed my dashboard. I got the axises, but that's it...
Is there a PHP dependency to some extension? GD maybe?

Thx

**Comment by ppaysant** [comment]
Hello @MightyCreak,

Thanks for your interest in dashboard and this feedback.

Some eventual possibilities explaining your problem:
- you have no data in database (for dashboard) as the cron job did not run yet
- you have only one day data, so no line can be draw
- you have more than on day data but with identical values (it's a bug from the graphic angular component I use : instead of drawing a flat line, it draws nothing)

For the first and second possibilities, the problem should be solved by now.
For the last one, this is a real bug that I do not see how to solve for now :(

Hope it helps.

Best regards

**Comment by MightyCreak** [comment]
It seems to be resolved! I did wait a little before posting this issue (2 or 3 days), but I think I fell in the third point: identical values.

Thanks!

**Comment by ppaysant** [comment]
Pleasure is mine :)

Hope I will have time to find a fix for this bug.
