### ISSUE TITLE
not showing values  when system turn ajax  to cron

### ISSUE THREAD

**Issue by renjithkathirolil** [CNRS-DSI-Dev/dashboard#22]
not displaying values in dashboard when the owncloud working on crontab

**Comment by ppaysant** [comment]
Hello @renjithkathirolil 

Thanks for this bug report.

There's a bug from the graphic angular component I use : instead of drawing a flat line, it draws nothing : it happens when first and last values are identical. That may be your pb.

This is a real bug that I did not see how to solve it for now :(

Regards

**Comment by ppaysant** [comment]
Graph component has been changed in V2. I close the issue

**Comment by mckaygerhard** [comment]
i try the stable 7 brand and seems does not solved any! the problem persist and the new code does not able to work in OC 7, the time between oc 9 and now oc 10 was little, i not have entouogh time to constants updates!

**Comment by ppaysant** [comment]
There won't be any fix for the OC7 version.
Sorry you don't have time to upgrade your owncloud. OC 10 is great :)

**Comment by mckaygerhard** [comment]
yeah i see some but take more resources.. also nextcloud its great too, but more resources.. seems there's a relation between take more resources and constants upgrades.. non-sense
